=== wkfff/WebConsolitation/Projects/DataPumps/Krista.FM.Server.DataPumps.CorrectedPumpBase/ClsHierarchy/ClsHierarchy.xsd
<?xml version="1.0" encoding="ISO-8859-5"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by mik-a-el (RPA Krista) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ClsHierarchy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ParentChildPair" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Линейный вид задания иерархии.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="Code" type="xs:int" use="required">
							<xs:annotation>
								<xs:documentation>Код элемента.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ParentCode" type="xs:int">
							<xs:annotation>
								<xs:documentation>Код родительского элемента.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ParentType">
		<xs:sequence>
			<xs:element name="HierarchyElement" type="ParentType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Родительский или подчиненный элемент иерахии. Тип элемента определяется его положением относительно других элементов xml.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:int" use="required">
			<xs:annotation>
				<xs:documentation>ID элемента</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== wkfff/WebConsolitation/Projects/DataPumps/Krista.FM.Server.DataPumps.CorrectedPumpBase/ClsHierarchy/d_MARKS_FNS29_2010.xml
<?xml version="1.0" encoding="ISO-8859-5"?>
<ClsHierarchy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClsHierarchy.xsd">
<ParentChildPair Code="10" ParentCode="1000"/>
<ParentChildPair Code="20" ParentCode="1000"/>
<ParentChildPair Code="30" ParentCode="1000"/>
<ParentChildPair Code="40" ParentCode="1000"/>
<ParentChildPair Code="50" ParentCode="1000"/>
<ParentChildPair Code="60" ParentCode="1000"/>
<ParentChildPair Code="70" ParentCode="1000"/>
<ParentChildPair Code="80" ParentCode="1000"/>
<ParentChildPair Code="90" ParentCode="1000"/>
<ParentChildPair Code="100" ParentCode="1000"/>
<ParentChildPair Code="110" ParentCode="1000"/>
<ParentChildPair Code="120" ParentCode="1000"/>
<ParentChildPair Code="130" ParentCode="1000"/>
<ParentChildPair Code="140" ParentCode="1000"/>
<ParentChildPair Code="150" ParentCode="1000"/>
<ParentChildPair Code="160" ParentCode="1000"/>
<ParentChildPair Code="170" ParentCode="1000"/>
<ParentChildPair Code="180" ParentCode="1000"/>
<ParentChildPair Code="190" ParentCode="1000"/>
<ParentChildPair Code="200" ParentCode="1000"/>
<ParentChildPair Code="210" ParentCode="1000"/>
<ParentChildPair Code="220" ParentCode="1000"/>
<ParentChildPair Code="230" ParentCode="1000"/>
<ParentChildPair Code="240" ParentCode="1000"/>
<ParentChildPair Code="250" ParentCode="1000"/>
<ParentChildPair Code="260" ParentCode="1000"/>
<ParentChildPair Code="270" ParentCode="1000"/>
<ParentChildPair Code="280" ParentCode="1000"/>
<ParentChildPair Code="290" ParentCode="1000"/>
<ParentChildPair Code="300" ParentCode="1000"/>
<ParentChildPair Code="310" ParentCode="1000"/>
<ParentChildPair Code="320" ParentCode="1000"/>
<ParentChildPair Code="330" ParentCode="1000"/>
<ParentChildPair Code="340" ParentCode="1000"/>
<ParentChildPair Code="350" ParentCode="1000"/>
<ParentChildPair Code="360" ParentCode="1000"/>
<ParentChildPair Code="370" ParentCode="1000"/>
<ParentChildPair Code="380" ParentCode="1000"/>
<ParentChildPair Code="390" ParentCode="1000"/>
<ParentChildPair Code="400" ParentCode="1000"/>
<ParentChildPair Code="410" ParentCode="1000"/>
<ParentChildPair Code="420" ParentCode="1000"/>
<ParentChildPair Code="430" ParentCode="1000"/>
<ParentChildPair Code="440" ParentCode="1000"/>
<ParentChildPair Code="450" ParentCode="1000"/>
<ParentChildPair Code="460" ParentCode="1000"/>
<ParentChildPair Code="470" ParentCode="1000"/>
<ParentChildPair Code="480" ParentCode="1000"/>
<ParentChildPair Code="490" ParentCode="1000"/>
<ParentChildPair Code="500" ParentCode="1000"/>
<ParentChildPair Code="510" ParentCode="1000"/>
<ParentChildPair Code="520" ParentCode="1000"/>
<ParentChildPair Code="530" ParentCode="1000"/>
<ParentChildPair Code="540" ParentCode="1000"/>
<ParentChildPair Code="550" ParentCode="1000"/>
<ParentChildPair Code="560" ParentCode="1000"/>
<ParentChildPair Code="570" ParentCode="1000"/>
<ParentChildPair Code="580" ParentCode="1000"/>
<ParentChildPair Code="590" ParentCode="1000"/>
<ParentChildPair Code="600" ParentCode="1000"/>
<ParentChildPair Code="610" ParentCode="1000"/>
<ParentChildPair Code="620" ParentCode="1000"/>
<ParentChildPair Code="630" ParentCode="1000"/>
<ParentChildPair Code="640" ParentCode="1000"/>
<ParentChildPair Code="650" ParentCode="1000"/>
<ParentChildPair Code="660" ParentCode="1000"/>
<ParentChildPair Code="670" ParentCode="1000"/>
<ParentChildPair Code="680" ParentCode="1000"/>
<ParentChildPair Code="690" ParentCode="1000"/>
</ClsHierarchy>
